### ISSUE TITLE
Play the game

### ISSUE THREAD

**Issue by Ziul** [start-x/startx-src#9]
# I wanna play the game on my pc!
### Issues Tracker:
- The Unity is not creating the /unity/builds/build7/build7_ovr-0.25_Data/x86_64/libmono.so
- Even if copy the file from #build2, we got a "Time out" exception

**Comment by chaws** [comment]
@Ziul I'm on it!

**Comment by chaws** [comment]
hahaha unfortunately none of ours computers run the Unity animation, only @gabrielanavarro 's, hence my constant obsession to preserve her PC's integrity =P
